import 'package:json_annotation/json_annotation.dart';

part 'subtitle.g.dart';

@JsonSerializable()
class PipedSubtitle {
  @JsonKey()
  final bool autoGenerated;
  @JsonKey()
  final String code;
  @JsonKey()
  final String mimeType;
  @JsonKey()
  final String name;
  @JsonKey()
  final String url;

  PipedSubtitle({
    required this.autoGenerated,
    required this.code,
    required this.mimeType,
    required this.name,
    required this.url,
  });

  factory PipedSubtitle.fromJson(Map<String, dynamic> json) =>
      _$PipedSubtitleFromJson(json);

  Map<String, dynamic> toJson() => _$PipedSubtitleToJson(this);
}
