// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'subtitle.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PipedSubtitle _$PipedSubtitleFromJson(Map<String, dynamic> json) =>
    PipedSubtitle(
      autoGenerated: json['autoGenerated'] as bool,
      code: json['code'] as String,
      mimeType: json['mimeType'] as String,
      name: json['name'] as String,
      url: json['url'] as String,
    );

Map<String, dynamic> _$PipedSubtitleToJson(PipedSubtitle instance) =>
    <String, dynamic>{
      'autoGenerated': instance.autoGenerated,
      'code': instance.code,
      'mimeType': instance.mimeType,
      'name': instance.name,
      'url': instance.url,
    };
